# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8607e7e2868cc7d33755c9e583ef5713f7868d67ca0279108481bbba10af720b7574f649dde5d3bf49f08e6690932837d924321b556d11b0067a0d6a9c75e4f6

test:
  secret_key_base: 1e1bd3e2196b75c561919eefb4876d2fd9a5584b9837a17037bfaa4ad970f6e8f57a59c63b010d82d368ba2211ea970bba1cd0552ba998c137e2ec6ad0cdb829

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
